#!/bin/bash

# Simple script to get AWS credentials in console with Multi-Factor Authentication.
# THIS SCRIPT JUST PRINTS EXPORT COMMANDS. PLEASE COPY THE COMMANDS AND EXECUTE BY YOURSELF.
#
# Command
# ./aws-mfa [YOUR_PROFLE_NAME] [YOUR_ACR] [MFA_CODE]
# Example
# ./aws-mfa.sh my-profile arn:aws:iam::xxxxxxxxxxxx:mfa/yyyyyyyyyyyyyyyyy 123456

# Set profile name as you like
profile=$1

# ACR code
# e.g. arn:aws:iam::xxxxxxxxxxxx:mfa/yyyyyyyyyyyyyyyyy
acr=$2

# Code generated by MFA device
token_code=$3

cache=$(mktemp)
aws sts get-session-token --serial-number $acr --token-code $token_code --profile $profile > $cache
cat << EOF
export AWS_ACCESS_KEY_ID=$(cat $cache | jq -r '.Credentials.AccessKeyId')
export AWS_SECRET_ACCESS_KEY=$(cat $cache | jq -r '.Credentials.SecretAccessKey')
export AWS_SESSION_TOKEN=$(cat $cache | jq -r '.Credentials.SessionToken')
export PS1="($profile) \$PS1"
EOF
rm $cache
